# Generated by Django 5.0.7 on 2024-07-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginId', models.CharField(max_length=16)),
                ('access_token', models.CharField(max_length=512)),
                ('expired_date', models.DateTimeField()),
                ('access_token_type', models.CharField(max_length=20)),
                ('expires_in', models.IntegerField()),
            ],
        ),
    ]
